name: CI (Public)

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cpu_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest

      - name: Lint
        run: |
          ruff --version
          ruff check . --select F,E9

      - name: Unit tests (no weights)
        run: |
          pytest -q

